Fix `ValueError` in Python 3.8 or newer
Validation has become stricter in Python 3.8.
So we need to pass `validate=False` to the constructor in this one case,
lest Python will print the following error message:

> ValueError: Invalid format 'a really silly format that discards the actual message' for '%' style